#include "module_util.h"
#include "module_imgui.h"
#include "module_imgui_ext.h"

#include <SDL.h>
#include <imgui.h>
#include <raylib.h>
#include <rlImGui.h>
#include <widgets.h>
#include <LuaBridge.h>
#include <imgui_stdlib.h>
#include <imgui_impl_sdl2.h>
#include <imgui_node_editor.h>
#include <imgui_impl_sdlrenderer2.h>

struct Bool
{
	bool val = false;
};

struct Int
{
	int val = 0;
};

struct Float
{
	float val = 0.0f;
};

struct CustomPayload
{
	luabridge::LuaRef payload;
	CustomPayload(luabridge::LuaRef _payload) : payload(_payload) { }
};

void init_imgui_module(lua_State* L)
{
	luabridge::getGlobalNamespace(L)
		.beginNamespace("Engine")
			.beginNamespace("ImGUI")
				// enum
				.beginNamespace("WindowFlags")
					.addVariable("None", ImGuiWindowFlags_None)
					.addVariable("NoTitleBar", ImGuiWindowFlags_NoTitleBar)
					.addVariable("NoResize", ImGuiWindowFlags_NoResize)
					.addVariable("NoMove", ImGuiWindowFlags_NoMove)
					.addVariable("NoScrollbar", ImGuiWindowFlags_NoScrollbar)
					.addVariable("NoScrollWithMouse", ImGuiWindowFlags_NoScrollWithMouse)
					.addVariable("NoCollapse", ImGuiWindowFlags_NoCollapse)
					.addVariable("AlwaysAutoResize", ImGuiWindowFlags_AlwaysAutoResize)
					.addVariable("NoBackground", ImGuiWindowFlags_NoBackground)
					.addVariable("NoSavedSettings", ImGuiWindowFlags_NoSavedSettings)
					.addVariable("NoMouseInputs", ImGuiWindowFlags_NoMouseInputs)
					.addVariable("MenuBar", ImGuiWindowFlags_MenuBar)
					.addVariable("HorizontalScrollbar", ImGuiWindowFlags_HorizontalScrollbar)
					.addVariable("NoFocusOnAppearing", ImGuiWindowFlags_NoFocusOnAppearing)
					.addVariable("NoBringToFrontOnFocus", ImGuiWindowFlags_NoBringToFrontOnFocus)
					.addVariable("AlwaysVerticalScrollbar", ImGuiWindowFlags_AlwaysVerticalScrollbar)
					.addVariable("AlwaysHorizontalScrollbar", ImGuiWindowFlags_AlwaysHorizontalScrollbar)
					.addVariable("NoNavInputs", ImGuiWindowFlags_NoNavInputs)
					.addVariable("NoNavFocus", ImGuiWindowFlags_NoNavFocus)
					.addVariable("UnsavedDocument", ImGuiWindowFlags_UnsavedDocument)
					.addVariable("NoDocking", ImGuiWindowFlags_NoDocking)
					.addVariable("NoNav", ImGuiWindowFlags_NoNav)
					.addVariable("NoDecoration", ImGuiWindowFlags_NoDecoration)
					.addVariable("NoInputs", ImGuiWindowFlags_NoInputs)
				.endNamespace()
				.beginNamespace("ChildFlags")
					.addVariable("None", ImGuiChildFlags_None)
					.addVariable("Borders", ImGuiChildFlags_Borders)
					.addVariable("AlwaysUseWindowPadding", ImGuiChildFlags_AlwaysUseWindowPadding)
					.addVariable("ResizeX", ImGuiChildFlags_ResizeX)
					.addVariable("ResizeY", ImGuiChildFlags_ResizeY)
					.addVariable("AutoResizeX", ImGuiChildFlags_AutoResizeX)
					.addVariable("AutoResizeY", ImGuiChildFlags_AutoResizeY)
					.addVariable("AlwaysAutoResize", ImGuiChildFlags_AlwaysAutoResize)
					.addVariable("FrameStyle", ImGuiChildFlags_FrameStyle)
				.endNamespace()
				.beginNamespace("StyleVar")
					.addVariable("Alpha", ImGuiStyleVar_Alpha)
					.addVariable("DisabledAlpha", ImGuiStyleVar_DisabledAlpha)
					.addVariable("WindowPadding", ImGuiStyleVar_WindowPadding)
					.addVariable("WindowRounding", ImGuiStyleVar_WindowRounding)
					.addVariable("WindowBorderSize", ImGuiStyleVar_WindowBorderSize)
					.addVariable("WindowMinSize", ImGuiStyleVar_WindowMinSize)
					.addVariable("WindowTitleAlign", ImGuiStyleVar_WindowTitleAlign)
					.addVariable("ChildRounding", ImGuiStyleVar_ChildRounding)
					.addVariable("ChildBorderSize", ImGuiStyleVar_ChildBorderSize)
					.addVariable("PopupRounding", ImGuiStyleVar_PopupRounding)
					.addVariable("PopupBorderSize", ImGuiStyleVar_PopupBorderSize)
					.addVariable("FramePadding", ImGuiStyleVar_FramePadding)
					.addVariable("FrameRounding", ImGuiStyleVar_FrameRounding)
					.addVariable("FrameBorderSize", ImGuiStyleVar_FrameBorderSize)
					.addVariable("ItemSpacing", ImGuiStyleVar_ItemSpacing)
					.addVariable("ItemInnerSpacing", ImGuiStyleVar_ItemInnerSpacing)
					.addVariable("IndentSpacing", ImGuiStyleVar_IndentSpacing)
					.addVariable("CellPadding", ImGuiStyleVar_CellPadding)
					.addVariable("ScrollbarSize", ImGuiStyleVar_ScrollbarSize)
					.addVariable("ScrollbarRounding", ImGuiStyleVar_ScrollbarRounding)
					.addVariable("GrabMinSize", ImGuiStyleVar_GrabMinSize)
					.addVariable("GrabRounding", ImGuiStyleVar_GrabRounding)
					.addVariable("TabRounding", ImGuiStyleVar_TabRounding)
					.addVariable("TabBarBorderSize", ImGuiStyleVar_TabBarBorderSize)
					.addVariable("ButtonTextAlign", ImGuiStyleVar_ButtonTextAlign)
					.addVariable("SelectableTextAlign", ImGuiStyleVar_SelectableTextAlign)
					.addVariable("SeparatorTextBorderSize", ImGuiStyleVar_SeparatorTextBorderSize)
					.addVariable("SeparatorTextAlign", ImGuiStyleVar_SeparatorTextAlign)
					.addVariable("SeparatorTextPadding", ImGuiStyleVar_SeparatorTextPadding)
					.addVariable("DockingSeparatorSize", ImGuiStyleVar_DockingSeparatorSize)
				.endNamespace()
				.beginNamespace("ImGuiCol")
					.addVariable("Text", ImGuiCol_Text)
					.addVariable("TextDisabled", ImGuiCol_TextDisabled)
					.addVariable("WindowBg", ImGuiCol_WindowBg)
					.addVariable("ChildBg", ImGuiCol_ChildBg)
					.addVariable("PopupBg", ImGuiCol_PopupBg)
					.addVariable("Border", ImGuiCol_Border)
					.addVariable("BorderShadow", ImGuiCol_BorderShadow)
					.addVariable("FrameBg", ImGuiCol_FrameBg)
					.addVariable("FrameBgHovered", ImGuiCol_FrameBgHovered)
					.addVariable("FrameBgActive", ImGuiCol_FrameBgActive)
					.addVariable("TitleBg", ImGuiCol_TitleBg)
					.addVariable("TitleBgActive", ImGuiCol_TitleBgActive)
					.addVariable("TitleBgCollapsed", ImGuiCol_TitleBgCollapsed)
					.addVariable("MenuBarBg", ImGuiCol_MenuBarBg)
					.addVariable("ScrollbarBg", ImGuiCol_ScrollbarBg)
					.addVariable("ScrollbarGrab", ImGuiCol_ScrollbarGrab)
					.addVariable("ScrollbarGrabHovered", ImGuiCol_ScrollbarGrabHovered)
					.addVariable("ScrollbarGrabActive", ImGuiCol_ScrollbarGrabActive)
					.addVariable("CheckMark", ImGuiCol_CheckMark)
					.addVariable("SliderGrab", ImGuiCol_SliderGrab)
					.addVariable("SliderGrabActive", ImGuiCol_SliderGrabActive)
					.addVariable("Button", ImGuiCol_Button)
					.addVariable("ButtonHovered", ImGuiCol_ButtonHovered)
					.addVariable("ButtonActive", ImGuiCol_ButtonActive)
					.addVariable("Header", ImGuiCol_Header)
					.addVariable("HeaderHovered", ImGuiCol_HeaderHovered)
					.addVariable("HeaderActive", ImGuiCol_HeaderActive)
					.addVariable("Separator", ImGuiCol_Separator)
					.addVariable("SeparatorHovered", ImGuiCol_SeparatorHovered)
					.addVariable("SeparatorActive", ImGuiCol_SeparatorActive)
					.addVariable("ResizeGrip", ImGuiCol_ResizeGrip)
					.addVariable("ResizeGripHovered", ImGuiCol_ResizeGripHovered)
					.addVariable("ResizeGripActive", ImGuiCol_ResizeGripActive)
					.addVariable("InputTextCursor", ImGuiCol_InputTextCursor)
					.addVariable("TabHovered", ImGuiCol_TabHovered)
					.addVariable("Tab", ImGuiCol_Tab)
					.addVariable("TabSelected", ImGuiCol_TabSelected)
					.addVariable("TabSelectedOverline", ImGuiCol_TabSelectedOverline)
					.addVariable("TabDimmed", ImGuiCol_TabDimmed)
					.addVariable("TabDimmedSelected", ImGuiCol_TabDimmedSelected)
					.addVariable("TabDimmedSelectedOverline", ImGuiCol_TabDimmedSelectedOverline)
					.addVariable("DockingPreview", ImGuiCol_DockingPreview)
					.addVariable("DockingEmptyBg", ImGuiCol_DockingEmptyBg)
					.addVariable("PlotLines", ImGuiCol_PlotLines)
					.addVariable("PlotLinesHovered", ImGuiCol_PlotLinesHovered)
					.addVariable("PlotHistogram", ImGuiCol_PlotHistogram)
					.addVariable("PlotHistogramHovered", ImGuiCol_PlotHistogramHovered)
					.addVariable("TableHeaderBg", ImGuiCol_TableHeaderBg)
					.addVariable("TableBorderStrong", ImGuiCol_TableBorderStrong)
					.addVariable("TableBorderLight", ImGuiCol_TableBorderLight)
					.addVariable("TableRowBg", ImGuiCol_TableRowBg)
					.addVariable("TableRowBgAlt", ImGuiCol_TableRowBgAlt)
					.addVariable("TextLink", ImGuiCol_TextLink)
					.addVariable("TextSelectedBg", ImGuiCol_TextSelectedBg)
					.addVariable("TreeLines", ImGuiCol_TreeLines)
					.addVariable("DragDropTarget", ImGuiCol_DragDropTarget)
					.addVariable("NavCursor", ImGuiCol_NavCursor)
					.addVariable("NavWindowingHighlight", ImGuiCol_NavWindowingHighlight)
					.addVariable("NavWindowingDimBg", ImGuiCol_NavWindowingDimBg)
					.addVariable("ModalWindowDimBg", ImGuiCol_ModalWindowDimBg)
				.endNamespace()
				.beginNamespace("ImGuiCond")
					.addVariable("None", ImGuiCond_None)
					.addVariable("Always", ImGuiCond_Always)
					.addVariable("Once", ImGuiCond_Once)
					.addVariable("FirstUseEver", ImGuiCond_FirstUseEver)
					.addVariable("Appearing", ImGuiCond_Appearing)
				.endNamespace()
				.beginNamespace("ImDrawFlags")
					.addVariable("None", ImDrawFlags_None)
					.addVariable("Closed", ImDrawFlags_Closed)
					.addVariable("RoundCornersTopLeft", ImDrawFlags_RoundCornersTopLeft)
					.addVariable("RoundCornersTopRight", ImDrawFlags_RoundCornersTopRight)
					.addVariable("RoundCornersBottomLeft", ImDrawFlags_RoundCornersBottomLeft)
					.addVariable("RoundCornersBottomRight", ImDrawFlags_RoundCornersBottomRight)
					.addVariable("RoundCornersNone", ImDrawFlags_RoundCornersNone)
					.addVariable("RoundCornersTop", ImDrawFlags_RoundCornersTop)
					.addVariable("RoundCornersBottom", ImDrawFlags_RoundCornersBottom)
					.addVariable("RoundCornersLeft", ImDrawFlags_RoundCornersLeft)
					.addVariable("RoundCornersRight", ImDrawFlags_RoundCornersRight)
					.addVariable("RoundCornersAll", ImDrawFlags_RoundCornersAll)
				.endNamespace()
				.beginNamespace("ConfigFlags")
					.addVariable("None", ImGuiConfigFlags_None)
					.addVariable("NavEnableKeyboard", ImGuiConfigFlags_NavEnableKeyboard)
					.addVariable("NavEnableGamepad", ImGuiConfigFlags_NavEnableGamepad)
					.addVariable("NoMouse", ImGuiConfigFlags_NoMouse)
					.addVariable("NoMouseCursorChange", ImGuiConfigFlags_NoMouseCursorChange)
					.addVariable("NoKeyboard", ImGuiConfigFlags_NoKeyboard)
					.addVariable("DockingEnable", ImGuiConfigFlags_DockingEnable)
					.addVariable("ViewportsEnable", ImGuiConfigFlags_ViewportsEnable)
				.endNamespace()
				.beginNamespace("InputTextFlags")
					.addVariable("None", ImGuiInputTextFlags_None)
					.addVariable("CharsDecimal", ImGuiInputTextFlags_CharsDecimal)
					.addVariable("CharsHexadecimal", ImGuiInputTextFlags_CharsHexadecimal)
					.addVariable("CharsScientific", ImGuiInputTextFlags_CharsScientific)
					.addVariable("CharsUppercase", ImGuiInputTextFlags_CharsUppercase)
					.addVariable("CharsNoBlank", ImGuiInputTextFlags_CharsNoBlank)
					.addVariable("AllowTabInput", ImGuiInputTextFlags_AllowTabInput)
					.addVariable("EnterReturnsTrue", ImGuiInputTextFlags_EnterReturnsTrue)
					.addVariable("EscapeClearsAll", ImGuiInputTextFlags_EscapeClearsAll)
					.addVariable("CtrlEnterForNewLine", ImGuiInputTextFlags_CtrlEnterForNewLine)
					.addVariable("ReadOnly", ImGuiInputTextFlags_ReadOnly)
					.addVariable("Password", ImGuiInputTextFlags_Password)
					.addVariable("AlwaysOverwrite", ImGuiInputTextFlags_AlwaysOverwrite)
					.addVariable("AutoSelectAll", ImGuiInputTextFlags_AutoSelectAll)
					.addVariable("ParseEmptyRefVal", ImGuiInputTextFlags_ParseEmptyRefVal)
					.addVariable("DisplayEmptyRefVal", ImGuiInputTextFlags_DisplayEmptyRefVal)
					.addVariable("NoHorizontalScroll", ImGuiInputTextFlags_NoHorizontalScroll)
					.addVariable("NoUndoRedo", ImGuiInputTextFlags_NoUndoRedo)
					.addVariable("ElideLeft", ImGuiInputTextFlags_ElideLeft)
				.endNamespace()
				.beginNamespace("SliderFlags")
					.addVariable("None", ImGuiSliderFlags_None)
					.addVariable("Logarithmic", ImGuiSliderFlags_Logarithmic)
					.addVariable("NoRoundToFormat", ImGuiSliderFlags_NoRoundToFormat)
					.addVariable("NoInput", ImGuiSliderFlags_NoInput)
					.addVariable("WrapAround", ImGuiSliderFlags_WrapAround)
					.addVariable("ClampOnInput", ImGuiSliderFlags_ClampOnInput)
					.addVariable("ClampZeroRange", ImGuiSliderFlags_ClampZeroRange)
					.addVariable("NoSpeedTweaks", ImGuiSliderFlags_NoSpeedTweaks)
					.addVariable("AlwaysClamp", ImGuiSliderFlags_AlwaysClamp)
				.endNamespace()
				.beginNamespace("HoveredFlags")
					.addVariable("None", ImGuiHoveredFlags_None)
					.addVariable("ChildWindows", ImGuiHoveredFlags_ChildWindows)
					.addVariable("RootWindow", ImGuiHoveredFlags_RootWindow)
					.addVariable("AnyWindow", ImGuiHoveredFlags_AnyWindow)
					.addVariable("NoPopupHierarchy", ImGuiHoveredFlags_NoPopupHierarchy)
					.addVariable("DockHierarchy", ImGuiHoveredFlags_DockHierarchy)
					.addVariable("AllowWhenBlockedByPopup", ImGuiHoveredFlags_AllowWhenBlockedByPopup)
					.addVariable("AllowWhenBlockedByActiveItem", ImGuiHoveredFlags_AllowWhenBlockedByActiveItem)
					.addVariable("AllowWhenOverlappedByItem", ImGuiHoveredFlags_AllowWhenOverlappedByItem)
					.addVariable("AllowWhenOverlappedByWindow", ImGuiHoveredFlags_AllowWhenOverlappedByWindow)
					.addVariable("AllowWhenDisabled", ImGuiHoveredFlags_AllowWhenDisabled)
					.addVariable("NoNavOverride", ImGuiHoveredFlags_NoNavOverride)
					.addVariable("AllowWhenOverlapped", ImGuiHoveredFlags_AllowWhenOverlapped)
					.addVariable("RectOnly", ImGuiHoveredFlags_RectOnly)
					.addVariable("RootAndChildWindows", ImGuiHoveredFlags_RootAndChildWindows)
					.addVariable("ForTooltip", ImGuiHoveredFlags_ForTooltip)
					.addVariable("Stationary", ImGuiHoveredFlags_Stationary)
					.addVariable("DelayNone", ImGuiHoveredFlags_DelayNone)
					.addVariable("DelayShort", ImGuiHoveredFlags_DelayShort)
					.addVariable("DelayNormal", ImGuiHoveredFlags_DelayNormal)
					.addVariable("NoSharedDelay", ImGuiHoveredFlags_NoSharedDelay)
				.endNamespace()
				.beginNamespace("SelectableFlags")
					.addVariable("None", ImGuiSelectableFlags_None)
					.addVariable("NoAutoClosePopups", ImGuiSelectableFlags_NoAutoClosePopups)
					.addVariable("SpanAllColumns", ImGuiSelectableFlags_SpanAllColumns)
					.addVariable("AllowDoubleClick", ImGuiSelectableFlags_AllowDoubleClick)
					.addVariable("Disabled", ImGuiSelectableFlags_Disabled)
					.addVariable("AllowOverlap", ImGuiSelectableFlags_AllowOverlap)
					.addVariable("Highlight", ImGuiSelectableFlags_Highlight)
				.endNamespace()
				.beginNamespace("PopupFlags")
					.addVariable("None", ImGuiPopupFlags_None)
					.addVariable("MouseButtonLeft", ImGuiPopupFlags_MouseButtonLeft)
					.addVariable("MouseButtonRight", ImGuiPopupFlags_MouseButtonRight)
					.addVariable("MouseButtonMiddle", ImGuiPopupFlags_MouseButtonMiddle)
					.addVariable("NoReopen", ImGuiPopupFlags_NoReopen)
					.addVariable("NoOpenOverExistingPopup", ImGuiPopupFlags_NoOpenOverExistingPopup)
					.addVariable("NoOpenOverItems", ImGuiPopupFlags_NoOpenOverItems)
					.addVariable("AnyPopupId", ImGuiPopupFlags_AnyPopupId)
					.addVariable("AnyPopupLevel", ImGuiPopupFlags_AnyPopupLevel)
					.addVariable("AnyPopup", ImGuiPopupFlags_AnyPopup)
				.endNamespace()
				.beginNamespace("TabBarFlags")
					.addVariable("None", ImGuiTabBarFlags_None)
					.addVariable("Reorderable", ImGuiTabBarFlags_Reorderable)
					.addVariable("AutoSelectNewTabs", ImGuiTabBarFlags_AutoSelectNewTabs)
					.addVariable("TabListPopupButton", ImGuiTabBarFlags_TabListPopupButton)
					.addVariable("NoCloseWithMiddleMouseButton", ImGuiTabBarFlags_NoCloseWithMiddleMouseButton)
					.addVariable("NoTabListScrollingButtons", ImGuiTabBarFlags_NoTabListScrollingButtons)
					.addVariable("NoTooltip", ImGuiTabBarFlags_NoTooltip)
					.addVariable("DrawSelectedOverline", ImGuiTabBarFlags_DrawSelectedOverline)
					.addVariable("FittingPolicyResizeDown", ImGuiTabBarFlags_FittingPolicyResizeDown)
					.addVariable("FittingPolicyScroll", ImGuiTabBarFlags_FittingPolicyScroll)
				.endNamespace()
				.beginNamespace("TabItemFlags")
					.addVariable("None", ImGuiTabItemFlags_None)
					.addVariable("UnsavedDocument", ImGuiTabItemFlags_UnsavedDocument)
					.addVariable("SetSelected", ImGuiTabItemFlags_SetSelected)
					.addVariable("NoCloseWithMiddleMouseButton", ImGuiTabItemFlags_NoCloseWithMiddleMouseButton)
					.addVariable("NoPushId", ImGuiTabItemFlags_NoPushId)
					.addVariable("NoTooltip", ImGuiTabItemFlags_NoTooltip)
					.addVariable("NoReorder", ImGuiTabItemFlags_NoReorder)
					.addVariable("Leading", ImGuiTabItemFlags_Leading)
					.addVariable("Trailing", ImGuiTabItemFlags_Trailing)
					.addVariable("NoAssumedClosure", ImGuiTabItemFlags_NoAssumedClosure)
				.endNamespace()
				.beginNamespace("TreeNodeFlags")
					.addVariable("None", ImGuiTreeNodeFlags_None)
					.addVariable("Selected", ImGuiTreeNodeFlags_Selected)
					.addVariable("Framed", ImGuiTreeNodeFlags_Framed)
					.addVariable("AllowOverlap", ImGuiTreeNodeFlags_AllowOverlap)
					.addVariable("NoTreePushOnOpen", ImGuiTreeNodeFlags_NoTreePushOnOpen)
					.addVariable("NoAutoOpenOnLog", ImGuiTreeNodeFlags_NoAutoOpenOnLog)
					.addVariable("DefaultOpen", ImGuiTreeNodeFlags_DefaultOpen)
					.addVariable("OpenOnDoubleClick", ImGuiTreeNodeFlags_OpenOnDoubleClick)
					.addVariable("OpenOnArrow", ImGuiTreeNodeFlags_OpenOnArrow)
					.addVariable("Leaf", ImGuiTreeNodeFlags_Leaf)
					.addVariable("Bullet", ImGuiTreeNodeFlags_Bullet)
					.addVariable("FramePadding", ImGuiTreeNodeFlags_FramePadding)
					.addVariable("SpanAvailWidth", ImGuiTreeNodeFlags_SpanAvailWidth)
					.addVariable("SpanFullWidth", ImGuiTreeNodeFlags_SpanFullWidth)
					.addVariable("SpanLabelWidth", ImGuiTreeNodeFlags_SpanLabelWidth)
					.addVariable("SpanAllColumns", ImGuiTreeNodeFlags_SpanAllColumns)
					.addVariable("LabelSpanAllColumns", ImGuiTreeNodeFlags_LabelSpanAllColumns)
					.addVariable("NavLeftJumpsToParent", ImGuiTreeNodeFlags_NavLeftJumpsToParent)
					.addVariable("CollapsingHeader", ImGuiTreeNodeFlags_CollapsingHeader)
				.endNamespace()
				.beginNamespace("DragDropFlags")
					.addVariable("None", ImGuiDragDropFlags_None)
					.addVariable("SourceNoPreviewTooltip", ImGuiDragDropFlags_SourceNoPreviewTooltip)
					.addVariable("SourceNoDisableHover", ImGuiDragDropFlags_SourceNoDisableHover)
					.addVariable("SourceNoHoldToOpenOthers", ImGuiDragDropFlags_SourceNoHoldToOpenOthers)
					.addVariable("SourceAllowNullID", ImGuiDragDropFlags_SourceAllowNullID)
					.addVariable("SourceExtern", ImGuiDragDropFlags_SourceExtern)
					.addVariable("PayloadAutoExpire", ImGuiDragDropFlags_PayloadAutoExpire)
					.addVariable("PayloadNoCrossContext", ImGuiDragDropFlags_PayloadNoCrossContext)
					.addVariable("PayloadNoCrossProcess", ImGuiDragDropFlags_PayloadNoCrossProcess)
					.addVariable("AcceptBeforeDelivery", ImGuiDragDropFlags_AcceptBeforeDelivery)
					.addVariable("AcceptNoDrawDefaultRect", ImGuiDragDropFlags_AcceptNoDrawDefaultRect)
					.addVariable("AcceptNoPreviewTooltip", ImGuiDragDropFlags_AcceptNoPreviewTooltip)
					.addVariable("AcceptPeekOnly", ImGuiDragDropFlags_AcceptPeekOnly)
				.endNamespace()
				.beginNamespace("ColorEditFlags")
					.addVariable("None", ImGuiColorEditFlags_None)
					.addVariable("NoAlpha", ImGuiColorEditFlags_NoAlpha)
					.addVariable("NoPicker", ImGuiColorEditFlags_NoPicker)
					.addVariable("NoOptions", ImGuiColorEditFlags_NoOptions)
					.addVariable("NoSmallPreview", ImGuiColorEditFlags_NoSmallPreview)
					.addVariable("NoInputs", ImGuiColorEditFlags_NoInputs)
					.addVariable("NoTooltip", ImGuiColorEditFlags_NoTooltip)
					.addVariable("NoLabel", ImGuiColorEditFlags_NoLabel)
					.addVariable("NoSidePreview", ImGuiColorEditFlags_NoSidePreview)
					.addVariable("NoDragDrop", ImGuiColorEditFlags_NoDragDrop)
					.addVariable("NoBorder", ImGuiColorEditFlags_NoBorder)
					.addVariable("AlphaOpaque", ImGuiColorEditFlags_AlphaOpaque)
					.addVariable("AlphaNoBg", ImGuiColorEditFlags_AlphaNoBg)
					.addVariable("AlphaPreviewHalf", ImGuiColorEditFlags_AlphaPreviewHalf)
					.addVariable("AlphaBar", ImGuiColorEditFlags_AlphaBar)
					.addVariable("HDR", ImGuiColorEditFlags_HDR)
					.addVariable("DisplayRGB", ImGuiColorEditFlags_DisplayRGB)
					.addVariable("DisplayHSV", ImGuiColorEditFlags_DisplayHSV)
					.addVariable("DisplayHex", ImGuiColorEditFlags_DisplayHex)
					.addVariable("Uint8", ImGuiColorEditFlags_Uint8)
					.addVariable("Float", ImGuiColorEditFlags_Float)
					.addVariable("PickerHueBar", ImGuiColorEditFlags_PickerHueBar)
					.addVariable("PickerHueWheel", ImGuiColorEditFlags_PickerHueWheel)
					.addVariable("InputRGB", ImGuiColorEditFlags_InputRGB)
					.addVariable("InputHSV", ImGuiColorEditFlags_InputHSV)
				.endNamespace()
				.beginNamespace("ComboFlags")
					.addVariable("None", ImGuiComboFlags_None)
					.addVariable("PopupAlignLeft", ImGuiComboFlags_PopupAlignLeft)
					.addVariable("HeightSmall", ImGuiComboFlags_HeightSmall)
					.addVariable("HeightRegular", ImGuiComboFlags_HeightRegular)
					.addVariable("HeightLarge", ImGuiComboFlags_HeightLarge)
					.addVariable("HeightLargest", ImGuiComboFlags_HeightLargest)
					.addVariable("NoArrowButton", ImGuiComboFlags_NoArrowButton)
					.addVariable("NoPreview", ImGuiComboFlags_NoPreview)
					.addVariable("WidthFitPreview", ImGuiComboFlags_WidthFitPreview)
				.endNamespace()
				.beginNamespace("ImGuiKey")
					.addVariable("None", ImGuiKey_None)
					.addVariable("Tab", ImGuiKey_Tab)
					.addVariable("LeftArrow", ImGuiKey_LeftArrow)
					.addVariable("RightArrow", ImGuiKey_RightArrow)
					.addVariable("UpArrow", ImGuiKey_UpArrow)
					.addVariable("DownArrow", ImGuiKey_DownArrow)
					.addVariable("PageUp", ImGuiKey_PageUp)
					.addVariable("PageDown", ImGuiKey_PageDown)
					.addVariable("Home", ImGuiKey_Home)
					.addVariable("End", ImGuiKey_End)
					.addVariable("Insert", ImGuiKey_Insert)
					.addVariable("DeleteImGuiKey_Delete", ImGuiKey_Delete)
					.addVariable("Backspace", ImGuiKey_Backspace)
					.addVariable("Space", ImGuiKey_Space)
					.addVariable("Enter", ImGuiKey_Enter)
					.addVariable("Escape", ImGuiKey_Escape)
					.addVariable("LeftCtrl", ImGuiKey_LeftCtrl)
					.addVariable("LeftShift", ImGuiKey_LeftShift)
					.addVariable("LeftAlt", ImGuiKey_LeftAlt)
					.addVariable("LeftSuper", ImGuiKey_LeftSuper)
					.addVariable("RightCtrl", ImGuiKey_RightCtrl)
					.addVariable("RightShift", ImGuiKey_RightShift)
					.addVariable("RightAlt", ImGuiKey_RightAlt)
					.addVariable("RightSuper", ImGuiKey_RightSuper)
					.addVariable("Menu", ImGuiKey_Menu)
					.addVariable("Num0", ImGuiKey_0)
					.addVariable("Num1", ImGuiKey_1)
					.addVariable("Num2", ImGuiKey_2)
					.addVariable("Num3", ImGuiKey_3)
					.addVariable("Num4", ImGuiKey_4)
					.addVariable("Num5", ImGuiKey_5)
					.addVariable("Num6", ImGuiKey_6)
					.addVariable("Num7", ImGuiKey_7)
					.addVariable("Num8", ImGuiKey_8)
					.addVariable("Num9", ImGuiKey_9)
					.addVariable("A", ImGuiKey_A)
					.addVariable("B", ImGuiKey_B)
					.addVariable("C", ImGuiKey_C)
					.addVariable("D", ImGuiKey_D)
					.addVariable("E", ImGuiKey_E)
					.addVariable("F", ImGuiKey_F)
					.addVariable("G", ImGuiKey_G)
					.addVariable("H", ImGuiKey_H)
					.addVariable("I", ImGuiKey_I)
					.addVariable("J", ImGuiKey_J)
					.addVariable("K", ImGuiKey_K)
					.addVariable("L", ImGuiKey_L)
					.addVariable("M", ImGuiKey_M)
					.addVariable("N", ImGuiKey_N)
					.addVariable("O", ImGuiKey_O)
					.addVariable("P", ImGuiKey_P)
					.addVariable("Q", ImGuiKey_Q)
					.addVariable("R", ImGuiKey_R)
					.addVariable("S", ImGuiKey_S)
					.addVariable("T", ImGuiKey_T)
					.addVariable("U", ImGuiKey_U)
					.addVariable("V", ImGuiKey_V)
					.addVariable("W", ImGuiKey_W)
					.addVariable("X", ImGuiKey_X)
					.addVariable("Y", ImGuiKey_Y)
					.addVariable("Z", ImGuiKey_Z)
					.addVariable("F1", ImGuiKey_F1)
					.addVariable("F2", ImGuiKey_F2)
					.addVariable("F3", ImGuiKey_F3)
					.addVariable("F4", ImGuiKey_F4)
					.addVariable("F5", ImGuiKey_F5)
					.addVariable("F6", ImGuiKey_F6)
					.addVariable("F7", ImGuiKey_F7)
					.addVariable("F8", ImGuiKey_F8)
					.addVariable("F9", ImGuiKey_F9)
					.addVariable("F10", ImGuiKey_F10)
					.addVariable("F11", ImGuiKey_F11)
					.addVariable("F12", ImGuiKey_F12)
					.addVariable("F13", ImGuiKey_F13)
					.addVariable("F14", ImGuiKey_F14)
					.addVariable("F15", ImGuiKey_F15)
					.addVariable("F16", ImGuiKey_F16)
					.addVariable("F17", ImGuiKey_F17)
					.addVariable("F18", ImGuiKey_F18)
					.addVariable("F19", ImGuiKey_F19)
					.addVariable("F20", ImGuiKey_F20)
					.addVariable("F21", ImGuiKey_F21)
					.addVariable("F22", ImGuiKey_F22)
					.addVariable("F23", ImGuiKey_F23)
					.addVariable("F24", ImGuiKey_F24)
					.addVariable("Apostrophe", ImGuiKey_Apostrophe)
					.addVariable("Comma", ImGuiKey_Comma)
					.addVariable("Minus", ImGuiKey_Minus)
					.addVariable("Period", ImGuiKey_Period)
					.addVariable("Slash", ImGuiKey_Slash)
					.addVariable("Semicolon", ImGuiKey_Semicolon)
					.addVariable("Equal", ImGuiKey_Equal)
					.addVariable("LeftBracket", ImGuiKey_LeftBracket)
					.addVariable("Backslash", ImGuiKey_Backslash)
					.addVariable("RightBracket", ImGuiKey_RightBracket)
					.addVariable("GraveAccent", ImGuiKey_GraveAccent)
					.addVariable("CapsLock", ImGuiKey_CapsLock)
					.addVariable("ScrollLock", ImGuiKey_ScrollLock)
					.addVariable("NumLock", ImGuiKey_NumLock)
					.addVariable("PrintScreen", ImGuiKey_PrintScreen)
					.addVariable("Pause", ImGuiKey_Pause)
					.addVariable("Keypad0", ImGuiKey_Keypad0)
					.addVariable("Keypad1", ImGuiKey_Keypad1)
					.addVariable("Keypad2", ImGuiKey_Keypad2)
					.addVariable("Keypad3", ImGuiKey_Keypad3)
					.addVariable("Keypad4", ImGuiKey_Keypad4)
					.addVariable("Keypad5", ImGuiKey_Keypad5)
					.addVariable("Keypad6", ImGuiKey_Keypad6)
					.addVariable("Keypad7", ImGuiKey_Keypad7)
					.addVariable("Keypad8", ImGuiKey_Keypad8)
					.addVariable("Keypad9", ImGuiKey_Keypad9)
					.addVariable("KeypadDecimal", ImGuiKey_KeypadDecimal)
					.addVariable("KeypadDivide", ImGuiKey_KeypadDivide)
					.addVariable("KeypadMultiply", ImGuiKey_KeypadMultiply)
					.addVariable("KeypadSubtract", ImGuiKey_KeypadSubtract)
					.addVariable("KeypadAdd", ImGuiKey_KeypadAdd)
					.addVariable("KeypadEnter", ImGuiKey_KeypadEnter)
					.addVariable("KeypadEqual", ImGuiKey_KeypadEqual)
					.addVariable("AppBack", ImGuiKey_AppBack)
					.addVariable("AppForward", ImGuiKey_AppForward)
					.addVariable("Oem102", ImGuiKey_Oem102)
					.addVariable("GamepadStart", ImGuiKey_GamepadStart)
					.addVariable("GamepadBack", ImGuiKey_GamepadBack)
					.addVariable("GamepadFaceLeft", ImGuiKey_GamepadFaceLeft)
					.addVariable("GamepadFaceRight", ImGuiKey_GamepadFaceRight)
					.addVariable("GamepadFaceUp", ImGuiKey_GamepadFaceUp)
					.addVariable("GamepadFaceDown", ImGuiKey_GamepadFaceDown)
					.addVariable("GamepadDpadLeft", ImGuiKey_GamepadDpadLeft)
					.addVariable("GamepadDpadRight", ImGuiKey_GamepadDpadRight)
					.addVariable("GamepadDpadUp", ImGuiKey_GamepadDpadUp)
					.addVariable("GamepadDpadDown", ImGuiKey_GamepadDpadDown)
					.addVariable("GamepadL1", ImGuiKey_GamepadL1)
					.addVariable("GamepadR1", ImGuiKey_GamepadR1)
					.addVariable("GamepadL2", ImGuiKey_GamepadL2)
					.addVariable("GamepadR2", ImGuiKey_GamepadR2)
					.addVariable("GamepadL3", ImGuiKey_GamepadL3)
					.addVariable("GamepadR3", ImGuiKey_GamepadR3)
					.addVariable("GamepadLStickLeft", ImGuiKey_GamepadLStickLeft)
					.addVariable("GamepadLStickRight", ImGuiKey_GamepadLStickRight)
					.addVariable("GamepadLStickUp", ImGuiKey_GamepadLStickUp)
					.addVariable("GamepadLStickDown", ImGuiKey_GamepadLStickDown)
					.addVariable("GamepadRStickLeft", ImGuiKey_GamepadRStickLeft)
					.addVariable("GamepadRStickRight", ImGuiKey_GamepadRStickRight)
					.addVariable("GamepadRStickUp", ImGuiKey_GamepadRStickUp)
					.addVariable("GamepadRStickDown", ImGuiKey_GamepadRStickDown)
					.addVariable("MouseLeft", ImGuiKey_MouseLeft)
					.addVariable("MouseRight", ImGuiKey_MouseRight)
					.addVariable("MouseMiddle", ImGuiKey_MouseMiddle)
					.addVariable("MouseX1", ImGuiKey_MouseX1)
					.addVariable("MouseX2", ImGuiKey_MouseX2)
					.addVariable("MouseWheelX", ImGuiKey_MouseWheelX)
					.addVariable("MouseWheelY", ImGuiKey_MouseWheelY)
				.endNamespace()
				.beginNamespace("NodeEditor")
					.beginNamespace("PinKind")
						.addVariable("Output", ax::NodeEditor::PinKind::Output)
						.addVariable("Input", ax::NodeEditor::PinKind::Input)
					.endNamespace()
					.beginNamespace("FlowDirection")
						.addVariable("Forward", ax::NodeEditor::FlowDirection::Forward)
						.addVariable("Backward", ax::NodeEditor::FlowDirection::Backward)
					.endNamespace()
					.beginNamespace("IconType")
						.addVariable("Flow", ax::Drawing::IconType::Flow)
						.addVariable("Circle", ax::Drawing::IconType::Circle)
						.addVariable("Square", ax::Drawing::IconType::Square)
						.addVariable("Grid", ax::Drawing::IconType::Grid)
						.addVariable("RoundSquare", ax::Drawing::IconType::RoundSquare)
						.addVariable("Diamond", ax::Drawing::IconType::Diamond)
					.endNamespace()
				.endNamespace()
				// usertype
				.beginClass<Bool>("Bool")
					.addProperty("val", &Bool::val, &Bool::val)
					.addConstructor(+[](void* ptr, bool val) { return new (ptr) Bool({ val }); },
						+[](void* ptr) { return new (ptr) Bool(); })
				.endClass()
				.beginClass<Int>("Int")
					.addProperty("val", &Int::val, &Int::val)
					.addConstructor(+[](void* ptr, int val) { return new (ptr) Int({ val }); },
						+[](void* ptr) { return new (ptr) Int(); })
				.endClass()
				.beginClass<Float>("Float")
					.addProperty("val", &Float::val, &Float::val)
					.addConstructor(+[](void* ptr, float val) { return new (ptr) Float({ val }); },
						+[](void* ptr) { return new (ptr) Float(); })
				.endClass()
				.beginClass<ImVec2>("ImVec2")
					.addProperty("x", &ImVec2::x, &ImVec2::x)
					.addProperty("y", &ImVec2::y, &ImVec2::y)
					.addConstructor(+[](void* ptr, float x, float y) { return new (ptr) ImVec2({ x, y }); },
						+[](void* ptr, const ImVec2& val) { return new (ptr) ImVec2(val); },
						+[](void* ptr) { return new (ptr) ImVec2(); })
				.endClass()
				.beginClass<ImVec4>("ImVec4")
					.addProperty("x", &ImVec4::x, &ImVec4::x)
					.addProperty("y", &ImVec4::y, &ImVec4::y)
					.addProperty("z", &ImVec4::z, &ImVec4::z)
					.addProperty("w", &ImVec4::w, &ImVec4::w)
					.addConstructor(+[](void* ptr, float x, float y, float z, float w) { return new (ptr) ImVec4({ x, y, z, w }); },
						+[](void* ptr, const ImVec4& val) { return new (ptr) ImVec4(val); },
						+[](void* ptr) { return new (ptr) ImVec4(); })
				.endClass()
				.beginClass<ImColor>("ImColor")
					.addProperty("value", &ImColor::Value, &ImColor::Value)
					.addFunction("to_u32", +[](const ImColor& color){ return ImU32(color); })
					.addFunction("from_hsv", +[](const ImColor& color, float h, float s, float v){ return color.HSV(h, s, v); })
					.addConstructor(+[](void* ptr, int r, int g, int b, int a) { return new (ptr) ImColor(r, g, b, a); },
						+[](void* ptr, const ImColor& color) { return new (ptr) ImColor(color); },
						+[](void* ptr, const ImVec4& color) { return new (ptr) ImColor(color); },
						+[](void* ptr) { return new (ptr) ImColor(); })
				.endClass()
				.beginClass<ImGuiIO>("ImGuiIO")
					.addProperty("ConfigFlags", &ImGuiIO::ConfigFlags, &ImGuiIO::ConfigFlags)
					.addProperty("KeyAlt", &ImGuiIO::KeyAlt, &ImGuiIO::KeyAlt)
					.addProperty("KeyCtrl", &ImGuiIO::KeyCtrl, &ImGuiIO::KeyCtrl)
					.addProperty("KeyShift", &ImGuiIO::KeyShift, &ImGuiIO::KeyShift)
				.endClass()
				.beginClass<ImGuiStyle>("ImGuiStyle")
					.addProperty("FontSizeBase", &ImGuiStyle::FontSizeBase, &ImGuiStyle::FontSizeBase)
					.addProperty("FontScaleMain", &ImGuiStyle::FontScaleMain, &ImGuiStyle::FontScaleMain)
					.addProperty("FontScaleDpi", &ImGuiStyle::FontScaleDpi, &ImGuiStyle::FontScaleDpi)
					.addProperty("Alpha", &ImGuiStyle::Alpha, &ImGuiStyle::Alpha)
					.addProperty("DisabledAlpha", &ImGuiStyle::DisabledAlpha, &ImGuiStyle::DisabledAlpha)
					.addProperty("WindowPadding", &ImGuiStyle::WindowPadding, &ImGuiStyle::WindowPadding)
					.addProperty("WindowRounding", &ImGuiStyle::WindowRounding, &ImGuiStyle::WindowRounding)
					.addProperty("WindowBorderSize", &ImGuiStyle::WindowBorderSize, &ImGuiStyle::WindowBorderSize)
					.addProperty("WindowBorderHoverPadding", &ImGuiStyle::WindowBorderHoverPadding, &ImGuiStyle::WindowBorderHoverPadding)
					.addProperty("WindowMinSize", &ImGuiStyle::WindowMinSize, &ImGuiStyle::WindowMinSize)
					.addProperty("WindowTitleAlign", &ImGuiStyle::WindowTitleAlign, &ImGuiStyle::WindowTitleAlign)
					.addProperty("WindowMenuButtonPosition", &ImGuiStyle::WindowMenuButtonPosition, &ImGuiStyle::WindowMenuButtonPosition)
					.addProperty("ChildRounding", &ImGuiStyle::ChildRounding, &ImGuiStyle::ChildRounding)
					.addProperty("ChildBorderSize", &ImGuiStyle::ChildBorderSize, &ImGuiStyle::ChildBorderSize)
					.addProperty("PopupRounding", &ImGuiStyle::PopupRounding, &ImGuiStyle::PopupRounding)
					.addProperty("PopupBorderSize", &ImGuiStyle::PopupBorderSize, &ImGuiStyle::PopupBorderSize)
					.addProperty("FramePadding", &ImGuiStyle::FramePadding, &ImGuiStyle::FramePadding)
					.addProperty("FrameRounding", &ImGuiStyle::FrameRounding, &ImGuiStyle::FrameRounding)
					.addProperty("FrameBorderSize", &ImGuiStyle::FrameBorderSize, &ImGuiStyle::FrameBorderSize)
					.addProperty("ItemSpacing", &ImGuiStyle::ItemSpacing, &ImGuiStyle::ItemSpacing)
					.addProperty("ItemInnerSpacing", &ImGuiStyle::ItemInnerSpacing, &ImGuiStyle::ItemInnerSpacing)
					.addProperty("CellPadding", &ImGuiStyle::CellPadding, &ImGuiStyle::CellPadding)
					.addProperty("TouchExtraPadding", &ImGuiStyle::TouchExtraPadding, &ImGuiStyle::TouchExtraPadding)
					.addProperty("IndentSpacing", &ImGuiStyle::IndentSpacing, &ImGuiStyle::IndentSpacing)
					.addProperty("ColumnsMinSpacing", &ImGuiStyle::ColumnsMinSpacing, &ImGuiStyle::ColumnsMinSpacing)
					.addProperty("ScrollbarSize", &ImGuiStyle::ScrollbarSize, &ImGuiStyle::ScrollbarSize)
					.addProperty("ScrollbarRounding", &ImGuiStyle::ScrollbarRounding, &ImGuiStyle::ScrollbarRounding)
					.addProperty("GrabMinSize", &ImGuiStyle::GrabMinSize, &ImGuiStyle::GrabMinSize)
					.addProperty("GrabRounding", &ImGuiStyle::GrabRounding, &ImGuiStyle::GrabRounding)
					.addProperty("LogSliderDeadzone", &ImGuiStyle::LogSliderDeadzone, &ImGuiStyle::LogSliderDeadzone)
					.addProperty("ImageBorderSize", &ImGuiStyle::ImageBorderSize, &ImGuiStyle::ImageBorderSize)
					.addProperty("TabRounding", &ImGuiStyle::TabRounding, &ImGuiStyle::TabRounding)
					.addProperty("TabBorderSize", &ImGuiStyle::TabBorderSize, &ImGuiStyle::TabBorderSize)
					.addProperty("TabCloseButtonMinWidthSelected", &ImGuiStyle::TabCloseButtonMinWidthSelected, &ImGuiStyle::TabCloseButtonMinWidthSelected)
					.addProperty("TabCloseButtonMinWidthUnselected", &ImGuiStyle::TabCloseButtonMinWidthUnselected, &ImGuiStyle::TabCloseButtonMinWidthUnselected)
					.addProperty("TabBarBorderSize", &ImGuiStyle::TabBarBorderSize, &ImGuiStyle::TabBarBorderSize)
					.addProperty("TabBarOverlineSize", &ImGuiStyle::TabBarOverlineSize, &ImGuiStyle::TabBarOverlineSize)
					.addProperty("TableAngledHeadersAngle", &ImGuiStyle::TableAngledHeadersAngle, &ImGuiStyle::TableAngledHeadersAngle)
					.addProperty("TableAngledHeadersTextAlign", &ImGuiStyle::TableAngledHeadersTextAlign, &ImGuiStyle::TableAngledHeadersTextAlign)
					.addProperty("TreeLinesFlags", &ImGuiStyle::TreeLinesFlags, &ImGuiStyle::TreeLinesFlags)
					.addProperty("TreeLinesSize", &ImGuiStyle::TreeLinesSize, &ImGuiStyle::TreeLinesSize)
					.addProperty("TreeLinesRounding", &ImGuiStyle::TreeLinesRounding, &ImGuiStyle::TreeLinesRounding)
					.addProperty("ColorButtonPosition", &ImGuiStyle::ColorButtonPosition, &ImGuiStyle::ColorButtonPosition)
					.addProperty("ButtonTextAlign", &ImGuiStyle::ButtonTextAlign, &ImGuiStyle::ButtonTextAlign)
					.addProperty("SelectableTextAlign", &ImGuiStyle::SelectableTextAlign, &ImGuiStyle::SelectableTextAlign)
					.addProperty("SeparatorTextBorderSize", &ImGuiStyle::SeparatorTextBorderSize, &ImGuiStyle::SeparatorTextBorderSize)
					.addProperty("SeparatorTextAlign", &ImGuiStyle::SeparatorTextAlign, &ImGuiStyle::SeparatorTextAlign)
					.addProperty("SeparatorTextPadding", &ImGuiStyle::SeparatorTextPadding, &ImGuiStyle::SeparatorTextPadding)
					.addProperty("DisplayWindowPadding", &ImGuiStyle::DisplayWindowPadding, &ImGuiStyle::DisplayWindowPadding)
					.addProperty("DisplaySafeAreaPadding", &ImGuiStyle::DisplaySafeAreaPadding, &ImGuiStyle::DisplaySafeAreaPadding)
					.addProperty("DockingSeparatorSize", &ImGuiStyle::DockingSeparatorSize, &ImGuiStyle::DockingSeparatorSize)
					.addProperty("MouseCursorScale", &ImGuiStyle::MouseCursorScale, &ImGuiStyle::MouseCursorScale)
					.addProperty("AntiAliasedLines", &ImGuiStyle::AntiAliasedLines, &ImGuiStyle::AntiAliasedLines)
					.addProperty("AntiAliasedLinesUseTex", &ImGuiStyle::AntiAliasedLinesUseTex, &ImGuiStyle::AntiAliasedLinesUseTex)
					.addProperty("AntiAliasedFill", &ImGuiStyle::AntiAliasedFill, &ImGuiStyle::AntiAliasedFill)
					.addProperty("CurveTessellationTol", &ImGuiStyle::CurveTessellationTol, &ImGuiStyle::CurveTessellationTol)
					.addProperty("CircleTessellationMaxError", &ImGuiStyle::CircleTessellationMaxError, &ImGuiStyle::CircleTessellationMaxError)
					//.addProperty("Colors", &ImGuiStyle::Colors, &ImGuiStyle::Colors)
					.addProperty("HoverStationaryDelay", &ImGuiStyle::HoverStationaryDelay, &ImGuiStyle::HoverStationaryDelay)
					.addProperty("HoverDelayShort", &ImGuiStyle::HoverDelayShort, &ImGuiStyle::HoverDelayShort)
					.addProperty("HoverDelayNormal", &ImGuiStyle::HoverDelayNormal, &ImGuiStyle::HoverDelayNormal)
					.addProperty("HoverFlagsForTooltipMouse", &ImGuiStyle::HoverFlagsForTooltipMouse, &ImGuiStyle::HoverFlagsForTooltipMouse)
					.addProperty("HoverFlagsForTooltipNav", &ImGuiStyle::HoverFlagsForTooltipNav, &ImGuiStyle::HoverFlagsForTooltipNav)
				.endClass()
				.beginClass<ImFont>("ImFont")
					
				.endClass()
				.beginClass<ImDrawList>("ImDrawList")
					.addFunction("AddRectFilled", +[](ImDrawList* draw_list, const ImVec2& p_min, const ImVec2& p_max, ImU32 col, luabridge::LuaRef rounding, luabridge::LuaRef flags)
						{ draw_list->AddRectFilled(p_min, p_max, col, rounding ? rounding : 0.0f, flags ? static_cast<ImDrawFlags>(flags) : 0); })
				.endClass()
				.beginClass<ImGuiViewport>("ImGuiViewport")
					.addProperty("ID", &ImGuiViewport::ID, &ImGuiViewport::ID)
					.addProperty("Flags", &ImGuiViewport::Flags, &ImGuiViewport::Flags)
					.addProperty("Pos", &ImGuiViewport::Pos, &ImGuiViewport::Pos)
					.addProperty("Size", &ImGuiViewport::Size, &ImGuiViewport::Size)
					.addProperty("WorkPos", &ImGuiViewport::WorkPos, &ImGuiViewport::WorkPos)
					.addProperty("WorkSize", &ImGuiViewport::WorkSize, &ImGuiViewport::WorkSize)
					.addProperty("DpiScale", &ImGuiViewport::DpiScale, &ImGuiViewport::DpiScale)
					.addProperty("ParentViewportId", &ImGuiViewport::ParentViewportId, &ImGuiViewport::ParentViewportId)
				.endClass()
				// extension: node-editor
				.beginNamespace("NodeEditor")
					.beginClass<ax::NodeEditor::Config>("Config")
						.addProperty("SettingsFile", &ax::NodeEditor::Config::SettingsFile, &ax::NodeEditor::Config::SettingsFile)
						.addConstructor<void()>()
					.endClass()
					.beginClass<ax::NodeEditor::EditorContext>("Context")

					.endClass()
					.beginClass<ax::NodeEditor::NodeId>("NodeId")
						.addFunction("get", +[](const ax::NodeEditor::NodeId& id) { return (size_t)id; })
						.addFunction("check_valid", +[](const ax::NodeEditor::NodeId& id) { return (bool)id; })
						.addConstructor(+[](void* ptr, size_t val) { return new (ptr) ax::NodeEditor::NodeId(val); },
							+[](void* ptr) { return new (ptr) ax::NodeEditor::NodeId(); })
					.endClass()
					.beginClass<ax::NodeEditor::PinId>("PinId")
						.addFunction("get", +[](const ax::NodeEditor::PinId& id) { return (size_t)id; })
						.addFunction("check_valid", +[](const ax::NodeEditor::PinId& id) { return (bool)id; })
						.addConstructor(+[](void* ptr, size_t val) { return new (ptr) ax::NodeEditor::PinId(val); },
							+[](void* ptr) { return new (ptr) ax::NodeEditor::PinId(); })
					.endClass()
					.beginClass<ax::NodeEditor::LinkId>("LinkId")
						.addFunction("get", +[](const ax::NodeEditor::LinkId& id) { return (size_t)id; })
						.addFunction("check_valid", +[](const ax::NodeEditor::LinkId& id) { return (bool)id; })
						.addConstructor(+[](void* ptr, size_t val) { return new (ptr) ax::NodeEditor::LinkId(val); },
							+[](void* ptr) { return new (ptr) ax::NodeEditor::LinkId(); })
					.endClass()
				.endNamespace()
				// example
				.addFunction("ShowDemoWindow", +[](luabridge::LuaRef open) { ImGui::ShowDemoWindow(open.isNil() ? nullptr : &open.cast<Bool*>().value()->val);})
				// config
				.addFunction("GetIO", ImGui::GetIO)
				// backend
				.addFunction("rlImGuiSetup", rlImGuiSetup)
				.addFunction("rlImGuiShutdown", rlImGuiShutdown)
				.addFunction("rlImGuiBegin", rlImGuiBegin)
				.addFunction("rlImGuiEnd", rlImGuiEnd)
				.addFunction("sdlImGuiSetup", +[](SDL_Window* window, SDL_Renderer* renderer)
					{
						ImGui::CreateContext();
						ImGui_ImplSDL2_InitForSDLRenderer(window, renderer);
						ImGui_ImplSDLRenderer2_Init(renderer);
					})
				.addFunction("sdlImGuiShutdown", +[]()
					{
						ImGui_ImplSDLRenderer2_Shutdown();
						ImGui_ImplSDL2_Shutdown();
						ImGui::DestroyContext();
					})
				.addFunction("sdlImGuiProcessEvent", ImGui_ImplSDL2_ProcessEvent)
				.addFunction("sdlImGuiBegin", +[]()
					{
						ImGui_ImplSDLRenderer2_NewFrame();
						ImGui_ImplSDL2_NewFrame();
						ImGui::NewFrame();
					})
				.addFunction("sdlImGuiEnd", +[](SDL_Renderer* renderer)
					{
						ImGui::Render();
						ImGui_ImplSDLRenderer2_RenderDrawData(ImGui::GetDrawData(), renderer);
					})
				// font
				.addFunction("AddFontFromFileTTF", +[](const char* filename)
					{
						ImFont* font = ImGui::GetIO().Fonts->AddFontFromFileTTF(filename, 0.0f, nullptr, ImGui::GetIO().Fonts->GetGlyphRangesChineseFull()); 
						if (font) ImGui::GetIO().Fonts->Build();
						return font;
					})
				.addFunction("PushFont", luabridge::overload<ImFont*, float>(ImGui::PushFont), luabridge::overload<ImFont*>(ImGui::PushFont))
				.addFunction("PopFont", ImGui::PopFont)
				// window
				.addFunction("GetMainViewport", ImGui::GetMainViewport)
				.addFunction("SetNextWindowPos", +[](const ImVec2& pos, luabridge::LuaRef cond, luabridge::LuaRef pivot) 
					{ ImGui::SetNextWindowPos(pos, cond ? static_cast<ImGuiCond>(cond) : 0, pivot ? pivot : ImVec2(0, 0)); })
				.addFunction("SetNextWindowSize", +[](const ImVec2& pos, luabridge::LuaRef cond) 
					{ ImGui::SetNextWindowSize(pos, cond ? static_cast<ImGuiCond>(cond) : 0); })
				.addFunction("SetNextWindowViewport", ImGui::SetNextWindowViewport)
				.addFunction("DockSpace", +[](ImGuiID dockspace_id, luabridge::LuaRef size, luabridge::LuaRef flags) 
					{ ImGui::DockSpace(dockspace_id, size ? size : ImVec2(0, 0), flags ? static_cast<ImGuiDockNodeFlags>(flags) : 0); })
				.addFunction("Begin", +[](const char* name, luabridge::LuaRef open, luabridge::LuaRef flags)
					{ return ImGui::Begin(name, open.isNil() ? nullptr : &open.cast<Bool*>().value()->val, flags.isNil() ? 0 : static_cast<ImGuiWindowFlags>(flags)); })
				.addFunction("End", ImGui::End)
				.addFunction("BeginChild", +[](const char* str_id, luabridge::LuaRef size, luabridge::LuaRef child_flgas, luabridge::LuaRef window_flags)
					{ return ImGui::BeginChild(str_id, size ? size : ImVec2(0, 0), child_flgas ? static_cast<ImGuiChildFlags>(child_flgas) : 0, window_flags ? static_cast<ImGuiWindowFlags>(window_flags) : 0); })
				.addFunction("EndChild", ImGui::EndChild)
				.addFunction("BeginTooltip", ImGui::BeginTooltip)
				.addFunction("EndTooltip", ImGui::EndTooltip)
				.addFunction("OpenPopup", +[](const char* str_id, luabridge::LuaRef flags) { ImGui::OpenPopup(str_id, flags ? static_cast<ImGuiPopupFlags>(flags) : 0); })
				.addFunction("BeginPopup", +[](const char* str_id, luabridge::LuaRef flags) { return ImGui::BeginPopup(str_id, flags ? static_cast<ImGuiWindowFlags>(flags) : 0); })
				.addFunction("EndPopup", ImGui::EndPopup)
				.addFunction("CollapsingHeader", +[](const char* label, luabridge::LuaRef flags) { return ImGui::CollapsingHeader(label, flags ? static_cast<ImGuiTreeNodeFlags>(flags) : 0);})
				// interaction
				.addFunction("IsItemHovered", +[](luabridge::LuaRef flags) { return ImGui::IsItemHovered(flags ? static_cast<ImGuiItemFlags>(flags) : 0); })
				.addFunction("IsAnyItemHovered", ImGui::IsAnyItemHovered)
				.addFunction("IsAnyItemActive", ImGui::IsAnyItemActive)
				.addFunction("IsKeyPressed", +[](int key, luabridge::LuaRef repeat) { return ImGui::IsKeyPressed((ImGuiKey)key, repeat.isNil() ? true : repeat); })
				.addFunction("IsKeyReleased", +[](int key) { return ImGui::IsKeyReleased((ImGuiKey)key); })
				.addFunction("IsWindowHovered", +[](luabridge::LuaRef flags) { return ImGui::IsWindowHovered(flags ? static_cast<ImGuiWindowFlags>(flags) : 0); })
				.addFunction("BeginDisabled", +[](luabridge::LuaRef disabled, lua_State* L) { ImGui::BeginDisabled(lua_gettop(L) == 0 ? true : disabled); })
				.addFunction("EndDisabled", ImGui::EndDisabled)
				.addFunction("IsItemDeactivated", ImGui::IsItemDeactivated)
				.addFunction("IsItemDeactivatedAfterEdit", ImGui::IsItemDeactivatedAfterEdit)
				.addFunction("BeginDragDropSource", +[](luabridge::LuaRef flags) { return ImGui::BeginDragDropSource(flags ? static_cast<ImGuiDragDropFlags>(flags) : 0); })
				.addFunction("EndDragDropSource", ImGui::EndDragDropSource)
				.addFunction("BeginDragDropTarget", ImGui::BeginDragDropTarget)
				.addFunction("EndDragDropTarget", ImGui::EndDragDropTarget)
				.addFunction("SetDragDropPayload", +[](const char* type, luabridge::LuaRef payload, luabridge::LuaRef cond)
					{
						CustomPayload* custom_payload = new CustomPayload(payload);
						return ImGui::SetDragDropPayload(type, &custom_payload, sizeof(CustomPayload*), cond ? static_cast<ImGuiCond>(cond) : 0);
					})
				.addFunction("AcceptDragDropPayload", +[](const char* type, luabridge::LuaRef flags, lua_State* L)
					{
						if (const ImGuiPayload* payload = ImGui::AcceptDragDropPayload(type, flags ? static_cast<ImGuiDragDropFlags>(flags) : 0))
						{
							CustomPayload* custom_payload = *((CustomPayload**)payload->Data);
							luabridge::LuaRef val = custom_payload->payload;
							delete custom_payload; custom_payload = nullptr;
							return val;
						}
						return luabridge::LuaRef(L, luabridge::LuaNil());
					})
				// widgets
				.addFunction("Spacing", ImGui::Spacing)
				.addFunction("Dummy", ImGui::Dummy)
				.addFunction("Bullet", ImGui::Bullet)
				.addFunction("Separator", ImGui::Separator)
				.addFunction("SetTooltip", +[](const char* text) { ImGui::SetTooltip(text); })
				.addFunction("BulletText", +[](const char* text) { ImGui::BulletText(text); })
				.addFunction("Text", +[](const char* text) { ImGui::TextUnformatted(text); })
				.addFunction("TextColored", +[](const ImVec4& color, const char* text) { ImGui::TextColored(color, text); })
				.addFunction("TextDisabled", +[](const char* text) { ImGui::TextDisabled(text); })
				.addFunction("SeparatorText", +[](const char* label) { ImGui::SeparatorText(label); })
				.addFunction("Checkbox", +[](const char* label, Bool* val) { return ImGui::Checkbox(label, &val->val); })
				.addFunction("RadioButton", +[](const char* label, bool val) { return ImGui::RadioButton(label, val); }, 
					+[](const char* label, Int* val, int num) { return ImGui::RadioButton(label, &val->val, num); })
				.addFunction("Button", +[](const char* label, luabridge::LuaRef size) { return ImGui::Button(label, size.isNil() ? ImVec2(0, 0) : size); })
				.addFunction("SmallButton", ImGui::SmallButton)
				.addFunction("ImageButton", 
					+[](const char* str_id, SDL_Texture* texture, const ImVec2& size, luabridge::LuaRef uv0, luabridge::LuaRef uv1, luabridge::LuaRef bg_col, luabridge::LuaRef tint_col)
						{ return ImGui::ImageButton(str_id, texture, size, uv0 ? uv0 : ImVec2(0, 0), uv1 ? uv1 : ImVec2(1, 1), bg_col ? bg_col : ImVec4(0, 0, 0, 0), tint_col ? tint_col : ImVec4(1, 1, 1, 1)); }, 
					+[](const char* str_id, const Texture& texture, const ImVec2& size, luabridge::LuaRef uv0, luabridge::LuaRef uv1, luabridge::LuaRef bg_col, luabridge::LuaRef tint_col)
						{ return ImGui::ImageButton(str_id, texture.id, size, uv0 ? uv0 : ImVec2(0, 0), uv1 ? uv1 : ImVec2(1, 1), bg_col ? bg_col : ImVec4(0, 0, 0, 0), tint_col ? tint_col : ImVec4(1, 1, 1, 1)); })
				.addFunction("Image", 
					+[](SDL_Texture* texture, const ImVec2& size, luabridge::LuaRef uv0, luabridge::LuaRef uv1, luabridge::LuaRef tint_col, luabridge::LuaRef border_col)
						{ ImGui::Image(texture, size, uv0 ? uv0 : ImVec2(0, 0), uv1 ? uv1 : ImVec2(1, 1), tint_col ? tint_col : ImVec4(1, 1, 1, 1), border_col ? border_col : ImVec4(0, 0, 0, 0)); },
					+[](const Texture& texture, const ImVec2& size, luabridge::LuaRef uv0, luabridge::LuaRef uv1, luabridge::LuaRef tint_col, luabridge::LuaRef border_col)
						{ ImGui::Image(texture.id, size, uv0 ? uv0 : ImVec2(0, 0), uv1 ? uv1 : ImVec2(1, 1), tint_col ? tint_col : ImVec4(1, 1, 1, 1), border_col ? border_col : ImVec4(0, 0, 0, 0)); })
				.addFunction("InputText", +[](const char* label, CString* str, luabridge::LuaRef flags) { return ImGui::InputText(label, &str->val, flags ? static_cast<ImGuiInputTextFlags>(flags) : 0); })
				.addFunction("InputTextMultiline", +[](const char* label, CString* str, const ImVec2& size, luabridge::LuaRef flags) { return ImGui::InputTextMultiline(label, &str->val, size, flags ? static_cast<ImGuiInputTextFlags>(flags) : 0); })
				.addFunction("InputFloat", +[](const char* label, Float* val, luabridge::LuaRef step, luabridge::LuaRef step_fast, luabridge::LuaRef format, luabridge::LuaRef flags)
					{ return ImGui::InputFloat(label, &val->val, step ? step : 0.0f, step_fast ? step_fast : 0.0f, format ? format.cast<const char*>().value() : "%.3f", flags ? static_cast<ImGuiInputTextFlags>(flags) : 0); })
				.addFunction("InputFloat2", +[](const char* label, ImVec2* val, luabridge::LuaRef format, luabridge::LuaRef flags)
					{ return ImGui::InputFloat2(label, &val->x, format ? format.cast<const char*>().value() : "%.3f", flags ? static_cast<ImGuiInputTextFlags>(flags) : 0); },
					+ [](const char* label, Float* val_1, Float* val_2, luabridge::LuaRef format, luabridge::LuaRef flags)
					{ 
						float val[] = { val_1->val, val_2->val };
						bool result = ImGui::InputFloat2(label, val, format ? format.cast<const char*>().value() : "%.3f", flags ? static_cast<ImGuiInputTextFlags>(flags) : 0);
						val_1->val = val[0], val_2->val = val[1];
						return result;
					})
				.addFunction("InputInt", +[](const char* label, Int* val, luabridge::LuaRef step, luabridge::LuaRef step_fast, luabridge::LuaRef format, luabridge::LuaRef flags)
					{ return ImGui::InputInt(label, &val->val, step ? step : 1, step_fast ? step_fast : 100, flags ? static_cast<ImGuiInputTextFlags>(flags) : 0); })
				.addFunction("DragInt", +[](const char* label, Int* val, luabridge::LuaRef speed, luabridge::LuaRef v_min, luabridge::LuaRef v_max, luabridge::LuaRef format, luabridge::LuaRef flags)
					{ return ImGui::DragInt(label, &val->val, speed ? speed : 1.0f, v_min ? static_cast<int>(v_min) : 0, v_max ? static_cast<int>(v_max) : 0, format ? format.cast<const char*>().value() : "%d", flags ? static_cast<ImGuiDragDropFlags>(flags) : 0); })
				.addFunction("DragInt2", +[](const char* label, Int* val_1, Int* val_2, luabridge::LuaRef speed, luabridge::LuaRef v_min, luabridge::LuaRef v_max, luabridge::LuaRef format, luabridge::LuaRef flags)
					{
						int val[] = { val_1->val, val_2->val };
						bool result = ImGui::DragInt2(label, val, speed ? speed : 1.0f, v_min.isNil() ? 0 : static_cast<int>(v_min), v_max.isNil() ? 0 : static_cast<int>(v_max),
							format ? format.cast<const char*>().value() : "%d", flags ? static_cast<ImGuiDragDropFlags>(flags) : 0);
						val_1->val = val[0], val_2->val = val[1];
						return result;
					})
				.addFunction("SliderInt", +[](const char* label, Int* val, luabridge::LuaRef v_min, luabridge::LuaRef v_max, luabridge::LuaRef format, luabridge::LuaRef flags)
					{ return ImGui::SliderInt(label, &val->val, v_min ? static_cast<int>(v_min) : 0, v_max ? static_cast<int>(v_max) : 0, format ? format.cast<const char*>().value() : "%d", flags ? static_cast<ImGuiSliderFlags>(flags) : 0); })
				.addFunction("Selectable", +[](const char* label, bool selected, luabridge::LuaRef flags, luabridge::LuaRef size)
					{ return ImGui::Selectable(label, selected, flags ? static_cast<ImGuiSelectableFlags>(flags) : 0, size ? size : ImVec2(0, 0)); })
				.addFunction("BeginTabBar", +[](const char* str_id, luabridge::LuaRef flags) { return ImGui::BeginTabBar(str_id, flags ? static_cast<ImGuiTabBarFlags>(flags) : 0); })
				.addFunction("EndTabBar", ImGui::EndTabBar)
				.addFunction("BeginTabItem", +[](const char* str_id, luabridge::LuaRef open, luabridge::LuaRef flags)
					{ return ImGui::BeginTabItem(str_id, open ? &open.cast<Bool*>().value()->val : nullptr, flags ? static_cast<ImGuiTabItemFlags>(flags) : 0); })
				.addFunction("EndTabItem", ImGui::EndTabItem)
				.addFunction("BeginMainMenuBar", ImGui::BeginMainMenuBar)
				.addFunction("EndMainMenuBar", ImGui::EndMainMenuBar)
				.addFunction("BeginMenuBar", ImGui::BeginMenuBar)
				.addFunction("EndMenuBar", ImGui::EndMenuBar)
				.addFunction("BeginMenu", +[](const char* label, luabridge::LuaRef enable) { return ImGui::BeginMenu(label, enable.isNil() ? true : enable); })
				.addFunction("EndMenu", ImGui::EndMenu)
				.addFunction("MenuItem", +[](const char* label, luabridge::LuaRef shortcut, luabridge::LuaRef selected, luabridge::LuaRef enabled)
					{ return ImGui::MenuItem(label, shortcut.isNil() ? nullptr : shortcut.cast<const char*>().value(), selected.isNil() ? false : static_cast<bool>(selected), enabled.isNil() ? true : enabled); })
				.addFunction("TreeNode", +[](const char* label) { return ImGui::TreeNode(label); }, +[](const char* label, int flags){ return ImGui::TreeNodeEx(label, flags); })
				.addFunction("TreePop", ImGui::TreePop)
				.addFunction("ColorEdit4", +[](const char* label, ImColor& color, luabridge::LuaRef flags) { return ImGui::ColorEdit4(label, &color.Value.x, flags ? static_cast<ImGuiColorEditFlags>(flags) : 0); })
				.addFunction("ColorPicker4", +[](const char* label, ImColor& color, luabridge::LuaRef flags) { return ImGui::ColorPicker4(label, &color.Value.x, flags ? static_cast<ImGuiColorEditFlags>(flags) : 0); })
				// style
				.addFunction("GetStyle", ImGui::GetStyle)
				.addFunction("PushStyleVar", luabridge::overload<ImGuiStyleVar, float>(ImGui::PushStyleVar), luabridge::overload<ImGuiStyleVar, const ImVec2&>(ImGui::PushStyleVar))
				.addFunction("PopStyleVar", +[](luabridge::LuaRef count) { ImGui::PopStyleVar(count ? count : 1); })
				.addFunction("PushStyleColor", luabridge::overload<ImGuiCol, const ImVec4&>(ImGui::PushStyleColor), luabridge::overload<ImGuiCol, ImU32>(ImGui::PushStyleColor))
				.addFunction("PopStyleColor", +[](luabridge::LuaRef count) { ImGui::PopStyleColor(count ? count : 1); })
				.addFunction("SetNextItemWidth", ImGui::SetNextItemWidth)
				.addFunction("PushTextWrapPos", ImGui::PushTextWrapPos)
				.addFunction("PopTextWrapPos", ImGui::PopTextWrapPos)
				.addFunction("Columns", +[](int count, luabridge::LuaRef id, luabridge::LuaRef border) 
					{ ImGui::Columns(count, id.isNil() ? nullptr : id.cast<const char*>().value(), border.isNil() ? true : border); })
				.addFunction("NextColumn", ImGui::NextColumn)
				.addFunction("SetColumnWidth", ImGui::SetColumnWidth)
				// layout
				.addFunction("GetMousePos", ImGui::GetMousePos)
				.addFunction("SetCursorPos", ImGui::SetCursorPos)
				.addFunction("GetCursorPos", ImGui::GetCursorPos)
				.addFunction("SetCursorScreenPos", ImGui::SetCursorScreenPos)
				.addFunction("GetCursorScreenPos", ImGui::GetCursorScreenPos)
				.addFunction("GetItemRectMin", ImGui::GetItemRectMin)
				.addFunction("GetItemRectMax", ImGui::GetItemRectMax)
				.addFunction("SetWindowSize", +[](const ImVec2& size, luabridge::LuaRef cond) { ImGui::SetWindowSize(size, cond ? static_cast<ImGuiCond>(cond) : 0); }, 
					+[](const char* name, const ImVec2& size, luabridge::LuaRef cond) { ImGui::SetWindowSize(name, size, cond ? static_cast<ImGuiCond>(cond) : 0); })
				.addFunction("GetWindowSize", ImGui::GetWindowSize)
				.addFunction("GetContentRegionAvail", ImGui::GetContentRegionAvail)
				.addFunction("GetTextLineHeight", ImGui::GetTextLineHeight)
				.addFunction("GetTextLineHeightWithSpacing", ImGui::GetTextLineHeightWithSpacing)
				.addFunction("CalcTextSize", +[](const char* text, luabridge::LuaRef hide_text_after_double_hash, luabridge::LuaRef wrap_width) 
					{ return ImGui::CalcTextSize(text, 0, hide_text_after_double_hash ? static_cast<bool>(hide_text_after_double_hash) : false, wrap_width ? wrap_width : -1.0f); })
				.addFunction("SameLine", +[](luabridge::LuaRef offset_from_start_x, luabridge::LuaRef spacing_w) 
					{ ImGui::SameLine(offset_from_start_x.isNil() ? 0.0f : offset_from_start_x, spacing_w.isNil() ? -1.0f : spacing_w); })
				.addFunction("BeginGroup", ImGui::BeginGroup)
				.addFunction("EndGroup", ImGui::EndGroup)
				.addFunction("AlignTextToFramePadding", ImGui::AlignTextToFramePadding)
				.addFunction("GetScrollX", ImGui::GetScrollX)
				.addFunction("GetScrollY", ImGui::GetScrollY)
				.addFunction("GetScrollMaxX", ImGui::GetScrollMaxX)
				.addFunction("GetScrollMaxY", ImGui::GetScrollMaxY)
				.addFunction("SetScrollHereX", ImGui::SetScrollHereX)
				.addFunction("SetScrollHereY", ImGui::SetScrollHereY)
				// other
				.addFunction("GetID", luabridge::overload<const char*>(ImGui::GetID), luabridge::overload<int>(ImGui::GetID))
				.addFunction("GetWindowDrawList", ImGui::GetWindowDrawList)
				// extension: node-editor
				.beginNamespace("NodeEditor")
					.addFunction("Create", +[](luabridge::LuaRef config)
						{ return ax::NodeEditor::CreateEditor(config.isNil() ? nullptr : config.cast<ax::NodeEditor::Config*>().value()); })
					.addFunction("Destroy", ax::NodeEditor::DestroyEditor)
					.addFunction("Suspend", ax::NodeEditor::Suspend)
					.addFunction("IsSuspended", ax::NodeEditor::IsSuspended)
					.addFunction("Resume", ax::NodeEditor::Resume)
					.addFunction("SetCurrentEditor", ax::NodeEditor::SetCurrentEditor)
					.addFunction("Begin", +[](const char* id, luabridge::LuaRef size) {	ax::NodeEditor::Begin(id, size.isNil() ? ImVec2(0, 0) : size); })
					.addFunction("End", ax::NodeEditor::End)
					.addFunction("GetNodePosition", ax::NodeEditor::GetNodePosition)
					.addFunction("SetNodePosition", ax::NodeEditor::SetNodePosition)
					.addFunction("GetNodeSize", ax::NodeEditor::GetNodeSize)
					.addFunction("CanvasToScreen", ax::NodeEditor::CanvasToScreen)
					.addFunction("ScreenToCanvas", ax::NodeEditor::ScreenToCanvas)
					.addFunction("CenterNodeOnScreen", ax::NodeEditor::CenterNodeOnScreen)
					.addFunction("BeginNode", ax::NodeEditor::BeginNode)
					.addFunction("EndNode", ax::NodeEditor::EndNode)
					.addFunction("BeginPin", +[](ax::NodeEditor::PinId id, int kind) { ax::NodeEditor::BeginPin(id, (ax::NodeEditor::PinKind)kind); })
					.addFunction("EndPin", ax::NodeEditor::EndPin)
					.addFunction("BeginCreate", +[](luabridge::LuaRef color, luabridge::LuaRef thickness)
						{ return ax::NodeEditor::BeginCreate(color.isNil() ? ImVec4(1, 1, 1, 1) : color, thickness.isNil() ? 1.0f : thickness); })
					.addFunction("EndCreate", ax::NodeEditor::EndCreate)
					.addFunction("QueryNewLink", +[](ax::NodeEditor::PinId* startId, ax::NodeEditor::PinId* endId, luabridge::LuaRef color, luabridge::LuaRef thickness)
						{
							if (!color && !thickness) return ax::NodeEditor::QueryNewLink(startId, endId);
							return ax::NodeEditor::QueryNewLink(startId, endId, color.cast<ImVec4>().value(), thickness ? thickness : 1.0f);
						})
					.addFunction("QueryNewNode", +[](ax::NodeEditor::PinId* pinId, luabridge::LuaRef color, luabridge::LuaRef thickness)
						{
							if (!color && !thickness) return ax::NodeEditor::QueryNewNode(pinId);
							return ax::NodeEditor::QueryNewNode(pinId, color.cast<ImVec4>().value(), thickness ? thickness : 1.0f);
						})
					.addFunction("AcceptNewItem", +[](luabridge::LuaRef color, luabridge::LuaRef thickness)
						{
							if (!color && !thickness) return ax::NodeEditor::AcceptNewItem();
							return ax::NodeEditor::AcceptNewItem(color.cast<ImVec4>().value(), thickness ? thickness : 1.0f);
						})
					.addFunction("RejectNewItem", +[](luabridge::LuaRef color, luabridge::LuaRef thickness)
						{
							if (!color && !thickness) return ax::NodeEditor::RejectNewItem();
							ax::NodeEditor::RejectNewItem(color.cast<ImVec4>().value(), thickness ? thickness : 1.0f);
						})
					.addFunction("Link", +[](ax::NodeEditor::LinkId id, ax::NodeEditor::PinId startPinId, ax::NodeEditor::PinId endPinId, luabridge::LuaRef color, luabridge::LuaRef thickness)
						{ return ax::NodeEditor::Link(id, startPinId, endPinId, color.isNil() ? ImVec4(1, 1, 1, 1) : color, thickness.isNil() ? 1.0f : thickness); })
					.addFunction("BeginDelete", ax::NodeEditor::BeginDelete)
					.addFunction("EndDelete", ax::NodeEditor::EndDelete)
					.addFunction("QueryDeletedLink", +[](ax::NodeEditor::LinkId* linkId, luabridge::LuaRef startId, luabridge::LuaRef endId)
						{ return ax::NodeEditor::QueryDeletedLink(linkId, startId.isNil() ? nullptr : startId.cast<ax::NodeEditor::PinId*>().value(), 
							endId.isNil() ? nullptr : endId.cast<ax::NodeEditor::PinId*>().value()); })
					.addFunction("QueryDeletedNode", ax::NodeEditor::QueryDeletedNode)
					.addFunction("AcceptDeletedItem", +[](luabridge::LuaRef deleteDependencies)
						{ return ax::NodeEditor::AcceptDeletedItem(deleteDependencies.isNil() ? true : deleteDependencies); })
					.addFunction("NavigateToContent", +[](luabridge::LuaRef duration)
						{ ax::NodeEditor::NavigateToContent(duration.isNil() ? -1.0f : duration); })
					.addFunction("NavigateToSelection", +[](luabridge::LuaRef zoom_in, luabridge::LuaRef duration)
						{ ax::NodeEditor::NavigateToSelection(zoom_in.isNil() ? false : static_cast<bool>(zoom_in), duration.isNil() ? -1.0f : duration); })
					.addFunction("HasSelectionChanged", ax::NodeEditor::HasSelectionChanged)
					.addFunction("GetSelectedObjectCount", ax::NodeEditor::GetSelectedObjectCount)
					//.addFunction("GetSelectedNodes", ax::NodeEditor::GetSelectedNodes)
					//.addFunction("GetSelectedLinks", ax::NodeEditor::GetSelectedLinks)
					.addFunction("IsNodeSelected", ax::NodeEditor::IsNodeSelected)
					.addFunction("IsLinkSelected", ax::NodeEditor::IsLinkSelected)
					.addFunction("ClearSelection", ax::NodeEditor::ClearSelection)
					.addFunction("SelectNode", +[](ax::NodeEditor::NodeId id, luabridge::LuaRef append) { ax::NodeEditor::SelectNode(id, append.isNil() ? false : static_cast<bool>(append)); })
					.addFunction("SelectLink", +[](ax::NodeEditor::LinkId id, luabridge::LuaRef append) { ax::NodeEditor::SelectLink(id, append.isNil() ? false : static_cast<bool>(append)); })
					.addFunction("DeselectNode", ax::NodeEditor::DeselectNode)
					.addFunction("DeselectLink", ax::NodeEditor::DeselectLink)
					.addFunction("RejectDeletedItem", ax::NodeEditor::RejectDeletedItem)
					.addFunction("Flow", +[](ax::NodeEditor::LinkId linkId, luabridge::LuaRef direction) 
						{ ax::NodeEditor::Flow(linkId, direction.isNil() ? ax::NodeEditor::FlowDirection::Forward : (ax::NodeEditor::FlowDirection)direction.cast<int>().value()); })
					.addFunction("Icon", +[](const ImVec2& size, int type, bool filled, luabridge::LuaRef color, luabridge::LuaRef innerColor)
						{ ax::Widgets::Icon(size, (ax::Drawing::IconType)type, filled, color.isNil() ? ImVec4(1, 1, 1, 1) : color, innerColor.isNil() ? ImVec4(0, 0, 0, 0) : innerColor); })
					.addFunction("AddNodeHeaderBackground", 
						+[](ax::NodeEditor::NodeId id, SDL_Texture* texture, const ImVec4& color, const ImVec2& min_rect, const ImVec2& max_rect)
						{
							int w, h; SDL_QueryTexture(texture, nullptr, nullptr, &w, &h);
							ImGUI_NodeEditor_AddNodeHeaderBackground(id, (ImTextureID)texture, ImVec2((float)w, (float)h), color, min_rect, max_rect);
						},
						+[](ax::NodeEditor::NodeId id, const Texture& texture, const ImVec4& color, const ImVec2& min_rect, const ImVec2& max_rect)
						{ ImGUI_NodeEditor_AddNodeHeaderBackground(id, (ImTextureID)texture.id, ImVec2((float)texture.width, (float)texture.height), color, min_rect, max_rect); })
					.addFunction("Comment", ImGUI_NodeEditor_Comment)
					.addFunction("ShowNodeContextMenu", ax::NodeEditor::ShowNodeContextMenu)
					.addFunction("ShowPinContextMenu", ax::NodeEditor::ShowPinContextMenu)
					.addFunction("ShowLinkContextMenu", ax::NodeEditor::ShowLinkContextMenu)
					.addFunction("ShowBackgroundContextMenu", ax::NodeEditor::ShowBackgroundContextMenu)
					.addFunction("ShowAllNodeID", ImGUI_NodeEditor_ShowAllNodeID)
				.endNamespace()
			.endNamespace()
		.endNamespace();
} 
